baseurl = "https://ben.land/"
languageCode = "en-us"
title = "ben.land"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
enableEmoji = true
enableGitInfo = true
footnoteReturnLinkContents = "â†©"
googleAnalytics = "G-V1LTGRZK1N"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 1
    
[[menu.main]]
    name = "Contact Info"
    url = "/contact/"
    weight = 2
    
[[menu.main]]
    name = "Resume/CV"
    url = "/resume/"
    weight = 3
    
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 4

[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5

[params]
    description = "Homepage for (and Physics / Programming blog by) Benjamin J. Land / BenLand100"
    footer = "Copyright 2020-2021 Benjamin J. Land"
